2024-02-22 09:49:28 : DEBUG : <module> : 439 : --- Start ---
2024-02-22 09:49:28 : DEBUG : load_ui : 405 : - Load UI -
2024-02-22 09:49:28 : ERROR : <module> : 447 : Failed
2024-02-22 09:49:28 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 444, in <module>
    load_ui()
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2024-02-22 09:49:28 : DEBUG : <module> : 451 : --- End ---
2024-02-22 09:57:17 : DEBUG : <module> : 439 : --- Start ---
2024-02-22 09:57:17 : DEBUG : load_ui : 405 : - Load UI -
2024-02-22 09:57:17 : ERROR : <module> : 447 : Failed
2024-02-22 09:57:17 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 444, in <module>
    load_ui()
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2024-02-22 09:57:17 : DEBUG : <module> : 451 : --- End ---
2024-02-22 10:03:00 : DEBUG : <module> : 439 : --- Start ---
2024-02-22 10:03:00 : DEBUG : load_ui : 405 : - Load UI -
2024-02-22 10:03:00 : ERROR : <module> : 447 : Failed
2024-02-22 10:03:00 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 444, in <module>
    load_ui()
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2024-02-22 10:03:00 : DEBUG : <module> : 451 : --- End ---
2024-02-22 10:03:17 : DEBUG : <module> : 439 : --- Start ---
2024-02-22 10:03:17 : DEBUG : load_ui : 405 : - Load UI -
2024-02-22 10:03:17 : ERROR : <module> : 447 : Failed
2024-02-22 10:03:17 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 444, in <module>
    load_ui()
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2024-02-22 10:03:17 : DEBUG : <module> : 451 : --- End ---
2024-02-22 10:12:03 : DEBUG : <module> : 439 : --- Start ---
2024-02-22 10:12:03 : DEBUG : load_ui : 405 : - Load UI -
2024-02-22 10:12:03 : ERROR : <module> : 447 : Failed
2024-02-22 10:12:03 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 444, in <module>
    load_ui()
  File "c:\Users\phili\AKS\AKS\GUI\calendar_widget.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2024-02-22 10:12:03 : DEBUG : <module> : 451 : --- End ---
